CREATE TABLE app_users (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    password_hash VARCHAR(255),
    display_name VARCHAR(255),
    organization VARCHAR(255),
    google_sub VARCHAR(255),
    role VARCHAR(32) NOT NULL DEFAULT 'USER',
    org_scope VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX uk_app_users_email ON app_users (email);
CREATE UNIQUE INDEX uk_app_users_google_sub ON app_users (google_sub);

CREATE TABLE volumes (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    owner_id VARCHAR(36) NOT NULL,
    display_name VARCHAR(512) NOT NULL,
    format VARCHAR(32) NOT NULL,
    stored_file_name VARCHAR(512) NOT NULL,
    size_bytes BIGINT NOT NULL,
    file_count INT NOT NULL DEFAULT 1,
    sha256 VARCHAR(64),
    deleted_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_volumes_owner FOREIGN KEY (owner_id) REFERENCES app_users (id)
);

CREATE INDEX idx_volumes_owner ON volumes (owner_id);

CREATE TABLE segmentation_jobs (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    owner_id VARCHAR(36) NOT NULL,
    volume_id VARCHAR(36) NOT NULL,
    volume_display_name VARCHAR(512) NOT NULL,
    model_type VARCHAR(128) NOT NULL,
    model_version VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    error_message VARCHAR(4000),
    output_file_name VARCHAR(512),
    notification_email VARCHAR(320),
    idempotency_key VARCHAR(128),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_jobs_owner FOREIGN KEY (owner_id) REFERENCES app_users (id),
    CONSTRAINT fk_jobs_volume FOREIGN KEY (volume_id) REFERENCES volumes (id)
);

CREATE INDEX idx_jobs_owner ON segmentation_jobs (owner_id);
CREATE INDEX idx_jobs_volume ON segmentation_jobs (volume_id);

CREATE TABLE job_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    message VARCHAR(4000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_job_events_job FOREIGN KEY (job_id) REFERENCES segmentation_jobs (id)
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id VARCHAR(36),
    action VARCHAR(128) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id VARCHAR(128),
    ip_address VARCHAR(64),
    detail VARCHAR(4000),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE idempotency_keys (
    idempotency_key VARCHAR(128) NOT NULL,
    owner_id VARCHAR(36) NOT NULL,
    job_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (owner_id, idempotency_key),
    CONSTRAINT fk_idempotency_job FOREIGN KEY (job_id) REFERENCES segmentation_jobs (id)
);

CREATE TABLE webhook_subscriptions (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    owner_id VARCHAR(36) NOT NULL,
    target_url VARCHAR(2048) NOT NULL,
    secret VARCHAR(256) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_webhook_owner FOREIGN KEY (owner_id) REFERENCES app_users (id)
);

CREATE INDEX idx_webhook_owner ON webhook_subscriptions (owner_id);
